### PR TITLE
Update .gitignore and add .nvmrc

### PR DESCRIPTION
**Pull request by fredlawl**
Update .gitignore with useful exclusions for various operating systems
and IDE's and text editors. Secondly, add .nvmrc.

### CODE REVIEW

**Comment by glitchedmob** [comment]
I'm a little confused with this one. The project already has both of these files. Why the changes?

**Comment by glitchedmob** [comment]
I am in favor of adding the .nvmrc though

**Comment by fredlawl** [comment]
Sorry, when I made the commit, I accidentally created the files under design folder first. Anyways, I always update .gitignores to these specifics because I use a variety of editors, and I don't like seeing unnecessary files being tracked about. As for the package-lock, same situation. I'll update this PR

**Comment by glitchedmob** [comment]
There's quite a few things in the .gitignore that we'll literally never need. I'll add a commit removing those and also adding some files for other code editors

**Review by glitchedmob — APPROVED** [review]

**Pull request merged**
